version: '2'

services:

    #fast-CGI processer manager
    php7:
        #build: ./docker/php-fpm
        image: php:7.0-fpm
        container_name: php-fpm
        networks:
            static-network:
                ipv4_address: 172.22.0.2
        ports:
            - "9000:9000"

        restart: always

    #nginx web app
    nginx:
        build: ./nginx
        image: khu/nginx
        container_name: nginx
        networks:
            static-network:
                ipv4_address: 172.22.0.4
        ports:
            - '80:80'
            - '443:443'
        volumes:
            #source app
            - ./var/www/web:/var/www/web
            #nginx conf
            - ./etc/nginx/conf.d:/etc/nginx/conf.d
        # depends_on: 
        #     - php7
        links:
            # - php7
            - httpd
        restart: always

    #apache web server
    httpd:
        build: ./httpd
        image: khu/httpd
        container_name: httpd
        networks:
            static-network:
                ipv4_address: 172.22.0.5
        ports:
            - '8080:8080'
        volumes:
            #source app
            - /var/www/web:/var/www/web
            - /etc/httpd/extra:/etc/httpd/conf/extra
            # - ./etc/httpd/logship.sh:/usr/local/logsplit.sh
        depends_on: 
            - php7
        links:
            - php7
        restart: always

    #MySQL config
    mysql:
        image: mysql
        environment:
            MYSQL_DATABASE: wordpress
            MYSQL_USER: user
            MYSQL_PASSWORD: pass
            MYSQL_ROOT_PASSWORD: pass
            MYSQL_ROOT_HOST: 0.0.0.0   
        container_name: mysql
        networks:
            static-network:
                ipv4_address: 172.22.0.3
        ports:
            - '3306:3306'
        volumes:
            - /var/lib/mysql:/var/lib/mysql
            - /etc/my.cnf:/etc/mysql/my.cnf
        restart: always

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.22.0.0/16
