version: '2.0'

services:
    #fast-CGI processer manager
    php7:
        build: ./docker/php-fpm
        # image: php:7.0-fpm
        container_name: php_fpm
        networks:
            static-network:
                ipv4_address: 172.22.0.2
        ports:
            - "9000:9000"
        volumes:
            - ./www:/var/www
        links:
            - mysql
        restart: always

    #nginx web app
    nginx:
        build: ./docker/nginx
        container_name: nginxserver
        networks:
            static-network:
                ipv4_address: 172.22.0.4
        ports:
            - '80:80'
            - '443:443'
        volumes:
            #source app
            - ./www:/var/www
            #nginx conf
            - ./etc/nginx/conf.d/virtual.conf:/etc/nginx/conf.d/virtual.conf
            - ./etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            
            - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
            #log    
            - ./logs/nginx:/var/log/nginx
        # depends_on: 
        #     - php7
        links:
            # - php7
            - httpd
        restart: always

    #apache web server
    httpd:
        build: ./docker/httpd
        container_name: httpdserver
        networks:
            static-network:
                ipv4_address: 172.22.0.5
        ports:
            - '8080:8080'
        volumes:
            #source app
            - ./www:/var/www
            #httpd conf
            - ./etc/httpd24/httpd.conf:/opt/rh/httpd24/root/etc/httpd/conf/httpd.conf
            - ./etc/httpd24/welcome.conf:/opt/rh/httpd24/root/etc/httpd/conf.d/welcome.conf
            - ./etc/httpd24/wpdocker.co.conf:/opt/rh/httpd24/root/etc/httpd/conf.d/wpdocker.co.conf
            - ./etc/httpd24/wp1.co.conf:/opt/rh/httpd24/root/etc/httpd/conf.d/wp1.co.conf
            #log    
            - ./logs/httpd24:/var/log/httpd24        
        depends_on: 
            - php7
        links:
            - php7
        restart: always

    #MySQL config
    mysql:
        image: mysql
        # build: ./docker/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=thaild
            - MYSQL_PASSWORD=thaild
            - MYSQL_DATABASE=wordpress
            - MYSQL_ROOT_HOST=0.0.0.0
        container_name: mysql
        networks:
            static-network:
                ipv4_address: 172.22.0.3
        ports:
            - '3306:3306'
        volumes:
            - ./db-data:/var/lib/mysql
        restart: always

        #PHPmyadmin
    myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "8282:80"
        networks:
            static-network:
                ipv4_address: 172.22.0.6
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
        restart: always
        depends_on:
            - mysql
volumes:
  db-data:
  www:

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.22.0.0/16
