version: '2'

services:
    # mautic:
    #     build: ./docker/mautic
    #     container_name: mauticserver
    #     networks:
    #         static-network:
    #             ipv4_address: 172.22.0.7
    #     links:
    #         - mysql:mysql
    #     depends_on:
    #         - mysql
    #     ports:
    #         - 8787:8787
    #     volumes:
    #         - ./www/mautic:/var/www
    #         #httpd conf
    #         - ./etc/mautic/httpd.conf:/opt/rh/httpd24/root/etc/httpd/conf/httpd.conf
    #         - ./etc/mautic/conf.d:/opt/rh/httpd24/root/etc/httpd/conf.d
    #         #log    
    #         - ./logs/mautic:/var/log/httpd24        
    #     environment:
    #         MAUTIC_DB_HOST: mysql
    #         MAUTIC_DB_USER: thaild
    #         MAUTIC_DB_PASSWORD: thaild
    #         MAUTIC_DB_NAME: mauticdb
    #     restart: always

    #fast-CGI processer manager
    php7:
        build: ./docker/php-fpm
        # image: php:7.0-fpm
        container_name: php_fpm
        networks:
            static-network:
                ipv4_address: 172.22.0.2
        ports:
            - "9000:9000"
        volumes:
            - ./www/httpd:/var/www
        links:
            - mysql
        restart: always

    #nginx web app
    nginx:
        build: ./docker/nginx
        container_name: nginxserver
        networks:
            static-network:
                ipv4_address: 172.22.0.4
        ports:
            - '80:80'
            - '443:443'
        volumes:
            #source app
            - ./www/httpd:/var/www
            #nginx conf
            - ./etc/nginx/conf.d:/etc/nginx/conf.d
            - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
            #log    
            - ./logs/nginx:/var/log/nginx
        # depends_on: 
        #     - php7
        links:
            # - php7
            - httpd
            # - mautic
        restart: always

    #apache web server
    httpd:
        build: ./docker/httpd
        container_name: httpdserver
        networks:
            static-network:
                ipv4_address: 172.22.0.5
        ports:
            - '8080:8080'
        volumes:
            #source app
            - ./www/httpd:/var/www
            #httpd conf
            - ./etc/httpd24/httpd.conf:/opt/rh/httpd24/root/etc/httpd/conf/httpd.conf
            - ./etc/httpd24/conf.d:/opt/rh/httpd24/root/etc/httpd/conf.d
            #log    
            - ./logs/httpd24:/var/log/httpd24        
        depends_on: 
            - php7
        links:
            - php7
        restart: always

    #MySQL config
    mysql:
        build: ./docker/mysql
        environment:
            MYSQL_DATABASE: wordpress
            MYSQL_USER: thaild
            MYSQL_PASSWORD: thaild
            MYSQL_ROOT_PASSWORD: root
            MYSQL_ROOT_HOST: 0.0.0.0   
        container_name: mysqlserver
        networks:
            static-network:
                ipv4_address: 172.22.0.3
        ports:
            - '3306:3306'
        volumes:
            - ./db-data:/var/lib/mysql
        restart: always
    
volumes:
  db-data:
  www:

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.22.0.0/16
