version: '2'

services:

    #fast-CGI processer manager
    php7.0:
        build: ./docker/php7.0-fpm
        # image: php:7.0-fpm
        container_name: php7.0-fpm
        networks:
            static-network:
                ipv4_address: 172.22.0.2
        ports:
            - "9000:9000"
        volumes:
            - ./www:/var/www
            - ./etc/php70/www.conf:/usr/local/etc/php-fpm.d/www.conf
        links:
            - mysql
        restart: always
    
    #fast-CGI processer manager
    php7.1:
        build: ./docker/php7.1-fpm
        # image: php:7.0-fpm
        container_name: php7.1-fpm
        networks:
            static-network:
                ipv4_address: 172.22.0.22
        ports:
            - "9071:9071"
        volumes:
            - ./www:/var/www
            - ./etc/php71/php-fpm.d:/usr/local/etc/php-fpm.d
        links:
            - mysql
        restart: always
    
    #PHP5.6
    php5.6:
        build: ./docker/php5.6-fpm
        # image: php:7.0-fpm
        container_name: php5.6-fpm
        networks:
            static-network:
                ipv4_address: 172.22.0.56
        ports:
            - "9056:9056"
        volumes:
            - ./www:/var/www
            - ./etc/php56/php-fpm.d:/etc/php-fpm.d
            - ./logs/php:/var/log/php-fpm
        links:
            - mysql
        restart: always

    #nginx web app
    nginx:
        build: ./docker/nginx
        container_name: nginxserver
        networks:
            static-network:
                ipv4_address: 172.22.0.4
        ports:
            - '80:80'
            - '443:443'
        volumes:
            #source app
            # - ./www:/var/www
            #nginx conf
            - ./etc/nginx/conf.d:/etc/nginx/conf.d
            - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
            #log    
            - ./logs/nginx:/var/log/nginx
        links:
            # - php7
            - httpd
            # - mautic
        restart: always

    #apache web server
    httpd:
        build: ./docker/httpd
        container_name: httpdserver
        networks:
            static-network:
                ipv4_address: 172.22.0.5
        ports:
            - '8080:8080'
        volumes:
            #source app
            - ./www:/var/www
            #httpd conf
            - ./etc/httpd/httpd.conf:/etc/httpd/conf/httpd.conf
            - ./etc/httpd/extra:/etc/httpd/conf/extra
            # - ./etc/httpd/logship.sh:/usr/local/logsplit.sh
            #log    
            - ./logs/httpd:/var/log/httpd      
        links:
            - php7.0
            - php7.1
            - php5.6
        restart: always

    #MySQL config
    mysql:
        build: ./docker/mysql
        environment:
            # MYSQL_DATABASE: wordpress
            # MYSQL_USER: thaild
            # MYSQL_PASSWORD: thaild
            MYSQL_ROOT_PASSWORD: root
            MYSQL_ROOT_HOST: 0.0.0.0   
        container_name: mysqlserver
        networks:
            static-network:
                ipv4_address: 172.22.0.3
        ports:
            - '3306:3306'
        volumes:
            - ./etc/mysql:/root
            - ./db-data:/var/lib/mysql
            - ./logs/mysql:/var/log/mysql
        restart: always
    
volumes:
  db-data:
  www:

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.22.0.0/16
