version: '2'

services:

    #fast-CGI processer manager
    php7:
        build: ./docker/php-fpm
        # image: php:7.0-fpm
        container_name: php-fpm
        networks:
            static-network:
                ipv4_address: 172.22.0.2
        ports:
            - "9000:9000"
        volumes:
            - ./www:/var/www
            - ./etc/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
        links:
            - mysql
        restart: always

    #nginx web app
    nginx:
        build: ./docker/nginx
        container_name: nginxserver
        networks:
            static-network:
                ipv4_address: 172.22.0.4
        ports:
            - '80:80'
            - '443:443'
        volumes:
            #source app
            # - ./www:/var/www
            #nginx conf
            - ./etc/nginx/conf.d:/etc/nginx/conf.d
            - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
            #log    
            - ./logs/nginx:/var/log/nginx
        links:
            # - php7
            - httpd
            # - mautic
        restart: always

    #apache web server
    httpd:
        build: ./docker/httpd
        container_name: httpdserver
        networks:
            static-network:
                ipv4_address: 172.22.0.5
        ports:
            - '8080:8080'
        volumes:
            #source app
            - ./www:/var/www
            #httpd conf
            - ./etc/httpd/httpd.conf:/etc/httpd/conf/httpd.conf
            - ./etc/httpd/httpd-vhosts.conf:/etc/httpd/conf/extra/httpd-vhosts.conf
            # - ./etc/httpd/logship.sh:/usr/local/logsplit.sh
            #log    
            - ./logs/httpd:/etc/httpd/logs       
        depends_on: 
            - php7
        links:
            - php7
        restart: always

    #MySQL config
    mysql:
        build: ./docker/mysql
        environment:
            MYSQL_DATABASE: wordpress
            MYSQL_USER: thaild
            MYSQL_PASSWORD: thaild
            MYSQL_ROOT_PASSWORD: root
            MYSQL_ROOT_HOST: 0.0.0.0   
        container_name: mysqlserver
        networks:
            static-network:
                ipv4_address: 172.22.0.3
        ports:
            - '3306:3306'
        volumes:
            - ./db-data:/var/lib/mysql
            - ./etc/mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
            - ./logs/mysql:/var/log/mysql
        restart: always
    
volumes:
  db-data:
  www:

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.22.0.0/16
