USE mysql;
-- GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
-- FLUSH PRIVILEGES;
-- UPDATE user SET password=PASSWORD("root") WHERE user='root';
-- FLUSH PRIVILEGES;

CREATE USER IF NOT EXISTS 'thaild'@'%' IDENTIFIED BY 'thaild';
GRANT ALL PRIVILEGES ON *.* TO 'thaild'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;