<?php
$parameters = array(
	'db_driver' => 'pdo_mysql',
	'db_host' => '172.22.0.3',
	'db_table_prefix' => null,
	'db_port' => '3306',
	'db_name' => 'hrautomail',
	'db_user' => 'thaild',
	'db_password' => 'thaild',
	'db_backup_tables' => 0,
	'db_backup_prefix' => 'bak_',
	'db_server_version' => '5.7.21',
	'mailer_from_name' => 'Lê Thái',
	'mailer_from_email' => 'thaiattt@gmail.com',
	'mailer_transport' => 'mail',
	'mailer_host' => null,
	'mailer_port' => null,
	'mailer_user' => 'mautic',
	'mailer_password' => 'mautic',
	'mailer_encryption' => null,
	'mailer_auth_mode' => null,
	'mailer_spool_type' => 'file',
	'mailer_spool_path' => '%kernel.root_dir%/spool',
	'secret_key' => '01db96e57ab8b4aa5dc375c50668c60953f849979ea05e6039f34827478c40f9',
	'site_url' => 'http://hrautomail.vicoders.com',
);
