<?php
$parameters = array(
	'db_driver' => 'pdo_mysql',
	'db_host' => '172.22.0.3',
	'db_table_prefix' => null,
	'db_port' => '3306',
	'db_name' => 'hrautomail',
	'db_user' => 'thaild',
	'db_password' => 'thaild',
	'db_backup_tables' => 0,
	'db_backup_prefix' => 'bak_',
	'db_server_version' => '5.7.21',
	'mailer_from_name' => 'Lê Thái',
	'mailer_from_email' => 'thaiattt@gmail.com',
	'mailer_transport' => 'mail',
	'mailer_host' => null,
	'mailer_port' => null,
	'mailer_user' => 'mautic',
	'mailer_password' => 'mautic',
	'mailer_encryption' => null,
	'mailer_auth_mode' => null,
	'mailer_spool_type' => 'file',
	'mailer_spool_path' => '%kernel.root_dir%/spool',
	'secret_key' => 'bd6ceb7644ac4cf9c3f60b0a808444d7eaef9baa5582f64ba64fad76cf8a3d09',
	'site_url' => 'http://hrautomail.vicoders.com:8787',
);
