<?php
$parameters = array(
	'db_driver' => 'pdo_mysql',
	'db_host' => '172.22.0.3',
	'db_table_prefix' => null,
	'db_port' => '3306',
	'db_name' => 'viwebsite',
	'db_user' => 'thaild',
	'db_password' => 'thaild',
	'db_backup_tables' => 0,
	'db_backup_prefix' => 'bak_',
	'db_server_version' => '5.7.21',
	'mailer_from_name' => 'Lê Thái',
	'mailer_from_email' => 'thaiattt@gmail.com',
	'mailer_transport' => 'mail',
	'mailer_host' => null,
	'mailer_port' => null,
	'mailer_user' => null,
	'mailer_password' => null,
	'mailer_encryption' => null,
	'mailer_auth_mode' => null,
	'mailer_spool_type' => 'memory',
	'mailer_spool_path' => '%kernel.root_dir%/spool',
	'secret_key' => '9279259b2d643f987e1ccd891ebab1733b678d9261c483409c5126389a35276a',
	'site_url' => 'http://viwebsite.vicoders.com',
);
